### ISSUE TITLE
upcoming czech localization - TimeGap Format issue

### ISSUE THREAD

**Issue by Amachik** [Lakr233/Saily#1]
_In my language u need to put the value(hours, minutes, days) in the middle._
So for example : "před (value) minutami"
### It is issue with: 

                       TimeGap_MinBefore
                       TimeGap_HoursBefore 
                       TimeGap_DaysBefore
                         
![image](https://user-images.githubusercontent.com/37242088/87674483-5a1ade00-c776-11ea-8368-61db3420ff25.png)

**Comment by Lakr233** [comment]
Fixed in 74f0899

Thanks for your hard work.
