### ISSUE TITLE
enhancement - design

### ISSUE THREAD

**Issue by Amachik** [Lakr233/Saily#11]
change Saily.WelcomeCard background color to dynamic(same as features background). White is too bright when darkmode enabled.

Also this cancel button is kinda dumb. Zero usage of it. Just taking space in app 
![D249DC8A-8318-4F61-95FC-6DBB8ACDD92B](https://user-images.githubusercontent.com/37242088/87848419-966a4d80-c8e0-11ea-9d6d-bf983ebe3164.png)

**Comment by Lakr233** [comment]
I will do the chage to the color, but not going to remove the Cancel button. Not everyone knows about it, the same as swiping to dissmiss a view controller.

**Comment by Lakr233** [comment]
Fixed.

**Comment by Amachik** [comment]
At least can u make it smaller? (The label of it)

**Comment by Lakr233** [comment]
NO

**Comment by Amachik** [comment]
Yep. Understand
