### ISSUE TITLE
avatar picker is broken 

### ISSUE THREAD

**Issue by ghost** [Lakr233/Saily#16]
it’s already a known issue but i added it so you won’t forget about it :P

**Comment by samrd-2** [comment]
Just wondering what is the avatar picker?

**Comment by ghost** [comment]
the thing that lets you set an avatar from your library

**Comment by DuyAnhComputer** [comment]
Tks

**Comment by ghost** [comment]
the avatar is [this](https://imgur.com/a/ZN1tDuh)

**Comment by Amachik** [comment]
Oh, but u have ur custom one

**Comment by ghost** [comment]
yep because i set it manually

**Comment by Amachik** [comment]
Oh, i see. So saily have problem with sandbox permissions?

**Comment by ghost** [comment]
that is correct

**Comment by Amachik** [comment]
I see.

**Comment by samrd-2** [comment]
How would I set it manually?

**Comment by Amachik** [comment]
Just change the png file. It is called i guess AppStoreIcon

**Comment by ghost** [comment]
no, put an image named avatar.png into /var/mobile/Documents/wiki.qaq.protein

**Comment by Amachik** [comment]
Lol i am dumb. She is right. My method is more complicated(and more retarded) I take advantage of else statement, ignoring if let...🙄😑

**Comment by Lakr233** [comment]
Done, release soon.
