### ISSUE TITLE
ios12 support for checkra1n

### ISSUE THREAD

**Issue by ghost** [Lakr233/Saily#18]
Have there ios12 support for checkra1n? (not rootlessjb one)
Thanks

**Comment by BreckenLusk** [comment]
Saily has not yet been tested with checkra1n on iOS 12. You're welcome to test this yourself if you'd like. Please try it out at your own risk. If you do decide to do this, please let us know if it works so we can update the compatibility list.

**Comment by ghost** [comment]
Try it just now but the firmware version was limited by the deb package of Saily 
Pre-Depends: firmware (>= 13.0), dpkg, uikittools, apt

**Comment by ghost** [comment]
i tested it two days ago, crashes upon launch @BreckenLusk

**Comment by BreckenLusk** [comment]
We will not be adding support for any versions of iOS or iPadOS lower than 13.0. This is due to incompatibilities with some required Swift libraries in iOS 12.
