### ISSUE TITLE
disable console log editing

### ISSUE THREAD

**Issue by ghost** [Lakr233/Saily#24]
you can select and edit the log as seen in [this screenshot](https://imgur.com/a/ZQ5Fx7v) which makes it impossible to reach the respring button as the keyboard won't hide anymore

**Comment by Amachik** [comment]
U can hide it by clicking on the Top Of the card where the Console label is placed🥴

**Comment by ghost** [comment]
why would you want to edit the log anyway? 😅

**Comment by Amachik** [comment]
True. Why? U right. It is useless. But like, copying log to debug it or for example if i want to send it to someone ...that´s actually a good reason to add some small button with copy log feature

**Comment by Lakr233** [comment]
Done, release soon.
