### ISSUE TITLE
Not so Critical dashboard bug

### ISSUE THREAD

**Issue by Amachik** [Lakr233/Saily#25]
So, when i open my dashboard i can not scroll down to see recently updated.

**Comment by ghost** [comment]
did you do anything else before? works fine for me 😅

**Comment by Amachik** [comment]
Weird. After restarting it is working great again.
Will look into it further.

**Comment by Lakr233** [comment]
There is a bug in dashboard layout that I have already noticed, but it doesnt appers frequently. I will fix it when I captured it.

**Comment by BreckenLusk** [comment]
Can you confirm everything is working fine?

**Comment by ghost** [comment]
i haven't had a single bug in the dashboard so far but let's wait for @Amachik 's reply 😊

**Comment by Lakr233** [comment]
Fixed, release soon.

**Comment by Amachik** [comment]
Sorry @Litteeen i was busy with python development so i forgot to reply. Bug is fixed for me. Working great again. I will test it further .
