### ISSUE TITLE
UI Improvement: buttons on "Add sources" page may be hidden

### ISSUE THREAD

**Issue by Skimige** [Lakr233/Saily#3]
On my device (iPad Pro 9.7-inch), the confirm/cancel buttons may just get out of the space, and can only be visible if the user scrolled down.

Screenshot:

![](https://user-images.githubusercontent.com/9017470/87761571-48077100-c844-11ea-9c6f-51d3cccc18ef.PNG)

**Comment by Lakr233** [comment]
Added, soon to be released.
