### ISSUE TITLE
Installed tweak sorting reverts to Name-Aa->Zz after closing and opening the app again 

### ISSUE THREAD

**Issue by samrd-2** [Lakr233/Saily#30]
When I change the sorting method for installed packages to latest it switches back to A->Z when I open the app again. I’m sure it’s a known issue but there’s no open issue for it and it still exists even in the latest beta so just put it

**Comment by Amachik** [comment]
We all knows

**Comment by samrd-2** [comment]
Yh ik but theres no open issue for it so thought it’d be useful to do one

**Comment by Lakr233** [comment]
Fixed 7aa79a9
