### ISSUE TITLE
Avatar picker still broken

### ISSUE THREAD

**Issue by Amachik** [Lakr233/Saily#31]
Heyy u completely deleted code block with avatar picking?

**Comment by Amachik** [comment]
Bcs if not, then ur fix for avatar picker is not working here.
Iphone 8 -red 64gb global ios 13.5.1

**Comment by samrd-2** [comment]
Same pressing pick avatar just brings up a blank grey screen for me too

**Comment by Lakr233** [comment]
It works on all of my devices don’t know why...

**Comment by Lakr233** [comment]
Fixed, release soon.

**Comment by Amachik** [comment]
@Co2333 @Litteeen I tried set 0777 permission to saily app and now it´s working. Weird.

**Comment by Lakr233** [comment]
🤷‍♂️ whatever, Im not using system image picker anymore!
