### ISSUE TITLE
Broken payment links crash Saily

### ISSUE THREAD

**Issue by yellowsink** [Lakr233/Saily#34]
If a package is marked as paid, but the link to proceed to payment does not exist, then Saily will crash on click of the "Purchase button"

**Comment by Lakr233** [comment]
Can you provide at least a sample of the package metadata? It would make life easier.

**Comment by Lakr233** [comment]
Can not reproduce the issue.
![Simulator Screen Shot - iPad mini (5th generation) - 2020-08-21 at 01 05 38](https://user-images.githubusercontent.com/25259084/90803036-bb703700-e34a-11ea-9392-2e21e93bdeeb.png)
