### ISSUE TITLE
Depiction links don’t work

### ISSUE THREAD

**Issue by ghost** [Lakr233/Saily#35]
![IMG_0629](https://user-images.githubusercontent.com/48258700/102323120-5c30d500-3f80-11eb-9fbe-4bf53984ee61.jpeg)

**Comment by Lakr233** [comment]
because I feeded the depiction view an empty view control to avoid reference counting issue, that leads to a serious memory leak, I'll add it back next up.

**Comment by Lakr233** [comment]
Fixed in 7aa79a9
