### ISSUE TITLE
random package updates and installed packages filing

### ISSUE THREAD

**Issue by samrd-2** [Lakr233/Saily#5]
[dpkg.zip](https://github.com/SailyTeam/Saily/files/4937537/dpkg.zip)

**Comment by Lakr233** [comment]
I have identified the issue. Will work on fixes. Additionally, a list of your repo would be helpful.

<img width="536" alt="截屏2020-07-17 下午10 38 59" src="https://user-images.githubusercontent.com/25259084/87798229-507c9d80-c87e-11ea-88a2-d8685a664f05.png">

**Comment by Lakr233** [comment]
A fix has been applied, release would be soon. If the issue still exists, reopen this issue.
