### ISSUE TITLE
Redesign Installed Tab

### ISSUE THREAD

**Issue by ghost** [Lakr233/Saily#7]
when selecting one of the sort options it won't be saved, means you have to sort it every time you view the list
https://imgur.com/a/flP1lBK

**Comment by Amachik** [comment]
But that´s up to u what do u prefer. I like it like it is. So some toggle in setting for " remember selected option" should be fine. Like i said. For me. This is not a bug. It´s just a what do u prefer on top of another

**Comment by ghost** [comment]
such a toggle would be convenient

**Comment by Lakr233** [comment]
The installed tab would be redesinged some days later. Currently it is a "hurry up" result :P

**Comment by Lakr233** [comment]
Completed 7aa79a9
